"""Smoke tests for `generate_wap_daily_brief` (no network — `--no-fetch` equivalent)."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from generate_wap_daily_brief import (  # noqa: E402
    _effective_feed_cap,
    build_daily_brief,
)

CONFIG = REPO / "docs" / "skill-work" / "work-strategy" / "daily-brief-config.json"


@pytest.mark.skipif(not CONFIG.exists(), reason="daily-brief-config.json not in tree")
def test_build_daily_brief_no_fetch_smoke():
    """Offline path: work-politics snapshot + strategy focus + empty RSS section; must not raise."""
    text = build_daily_brief(
        "grace-mar",
        fetch_feeds=False,
        config_path=CONFIG,
        max_age_hours=36,
        max_items_display=10,
        story_dedupe_enabled=True,
        max_per_feed_override=None,
    )
    assert text.startswith("# Daily brief")
    assert "## 1. Work-politics snapshot" in text
    assert "## 1b. Work-strategy focus" in text
    assert "## 2. Headlines (ingested RSS)" in text
    assert "RSS skipped" in text
    assert "## 3. Lead themes" in text
    assert "## 6. Next actions" in text
    assert "Generated by `scripts/generate_wap_daily_brief.py`" in text


def test_effective_feed_cap_override_and_explicit():
    caps = {
        "default_max_items_per_feed": 12,
        "max_items_by_tier": {1: 14, 2: 10, 3: 6},
    }
    assert _effective_feed_cap({"tier": 3, "max_items": None}, caps, override=5) == 5
    assert _effective_feed_cap({"tier": 1, "max_items": 3}, caps, None) == 3
    assert _effective_feed_cap({"tier": 3, "max_items": None}, caps, None) == 6
    assert _effective_feed_cap({"tier": 2, "max_items": None}, caps, None) == 10
