"""Phrase and token replacements for Predictive History ASR transcripts.

Edit this file when systematic mis-hearings show up on new ingests.
Replacement order is applied longest-first within each tier to avoid
partial matches (handled by the normalizer).

**Civilization** tier includes aggressive fixes (e.g. “thieves” → “Thebes”) that
must NOT run on Geo-Strategy transcripts — use series detection from filename.
"""

from __future__ import annotations

# Safe on any series (IR, geography, generic English glitches).
COMMON_REPLACEMENTS: list[tuple[str, str]] = [
    # Long / phrase first
    ("Memnon of RADS", "Memnon of Rhodes"),
    ("men of RADS", "Memnon of Rhodes"),
    ("men of Road set sail", "Memnon of Rhodes set sail"),
    ("men of roads", "Memnon of Rhodes"),
    ("men of Rose", "Memnon of Rhodes"),
    ("men of world set sail", "Memnon of Rhodes set sail"),
    ("when man of Rose Dies", "when Memnon of Rhodes dies"),
    ("Mena roads", "Memnon of Rhodes"),
    ("Men on of roads", "Memnon of Rhodes"),
    ("Menan of RADS", "Memnon of Rhodes"),
    ("what men Road proposes", "what Memnon proposes"),
    ("Cleopatra uidic", "Cleopatra Eurydice"),
    ("granticus", "Granicus"),
    ("battle of granticus", "battle of Granicus"),
    ("Battle of granticus", "Battle of Granicus"),
    ("grakis", "Granicus"),
    ("guacola", "Gaugamela"),
    ("gamola", "Gaugamela"),
    ("guaga", "Gaugamela"),
    ("guala", "Gaugamela"),
    ("Battle of Isis ", "Battle of Issus "),
    ("battles Isis ", "battles Issus "),
    ("Isis and and", "Issus and"),
    ("both battles Isis ", "both battles Issus "),
    ("cus black clus the black", "Cleitus the Black"),
    ("C is a black", "Cleitus the Black"),
    ("C as of black", "Cleitus the Black"),
    ("clus a black", "Cleitus the Black"),
    ("ctis of black", "Cleitus the Black"),
    ("cl of black", "Cleitus the Black"),
    ("class of black", "Cleitus the Black"),
    ("paronan", "Parmenion"),
    ("permon", "Parmenion"),
    ("parmonian", "Parmenion"),
    ("paronian", "Parmenion"),
    ("ponan", "Parmenion"),
    ("P pan", "Parmenion"),
    ("harmonia", "Parmenion"),
    ("olympas", "Olympias"),
    ("olympius", "Olympias"),
    ("EDC and her daughter", "Eurydice and her daughter"),
    ("your DC and Phillip", "Eurydice and Philip"),
    ("Attlas", "Attalus"),
    ("Theus do now", "Darius do now"),
    ("what does Theus", "what does Darius"),
    ("Moses forces", "most forces"),
    ("tamland", "Tamerlane"),
    ("dynastes", "dynasts"),
    ("isolate Oasis", "Siwa Oasis"),
    (" a syesis", " syncretism"),
    ("33 oce ", "330 BCE "),
    ("33c uh BCE", "336 BCE"),
    ("33c uh 336", "336"),
    ("gangas Khan", "Genghis Khan"),
    (" napan ", " Napoleon "),
    ("anal Tools", "analytical tools"),
    ("anal model", "analytical model"),
    ("anical model", "analytical model"),
    ("an antical model", "an analytical model"),
    ("Crow history", "through history"),
    ("calvalry", "cavalry"),
    ("calary", "cavalry"),
    ("SAT trops", "satraps"),
    ("SAT traps", "satraps"),
    ("Sops are", "satraps are"),
    ("stup's arm", "satrap's arm"),
    ("One S was about", "One satrap was about"),
    ("Eternal descent", "internal dissent"),
    ("self C's problem", "South Korea's problem"),
    ("self Korea", "South Korea"),
    ("self create", "South Korea"),
    ("F trility rate", "fertility rate"),
    ("low parate", "low birthrate"),
    ("he was a keymaker", "he was a kingmaker"),
    ("F lius Fus", "Philotas"),
    ("Phil fetas", "Philotas"),
    ("fites", "Philotas"),
    ("Mason Army", "Macedonian Army"),
    ("masonian", "Macedonian"),
    ("maonan", "Macedonian"),
    ("323 AER dies", "323 Alexander dies"),
    ("temperature Sun", "Iolaus"),
    ("this c a problem", "this created a problem"),
    ("caran mix", "Parmenion"),
    ("faithful decision", "fateful decision"),
    ("yria which is in North", "Illyria which is in North"),
    ("hoplight", "hoplite"),
    ("deop discipline", "develop discipline"),
    ("weren fighting", "weren't fighting"),
    ("trouble armies", "tribal armies"),
    ("a trial Army", "a tribal army"),
    ("darus ", "Darius "),
    ("darus commits", "Darius commits"),
    (" the persons flee", " the Persians flee"),
    ("spart to rebel", "Sparta to rebel"),
    (" spart ", " Sparta "),
    ("PHX", "phalanx"),
    # tokens
    ("permania", "Parmenion"),
]

# Greek / ancient history strand only — run when filename matches civilization-*.md
CIVILIZATION_REPLACEMENTS: list[tuple[str, str]] = [
    ("Sacred Band of Thieves", "Sacred Band of Thebes"),
    ("sacred Band of Thieves", "Sacred Band of Thebes"),
    ("sacred ban of Thieves", "Sacred Band of Thebes"),
    ("sacred Ben of Thieves", "Sacred Band of Thebes"),
    ("the SEC B thieves", "the Sacred Band"),
    ("SEC B thieves", "Sacred Band"),
    ("Battle of Tonia Tania", "Battle of Chaeronea"),
    ("battle of Sheria", "battle of Chaeronea"),
    ("so in Tania", "at Chaeronea"),
    (" in Tania ", " at Chaeronea "),
    ("palan war", "Peloponnesian War"),
    ("pelian war", "Peloponnesian War"),
    ("theevans", "Thebans"),
    ("thians", "Thebans"),
    ("primarily uh by a\nthe great", "primarily uh by Alexander the Great"),
    ("how did a the great", "how did Alexander the Great"),
    ("ex ex the great", "Alexander the Great"),
    ("macedone", "Macedon"),
    ("kingdom of ma Macedonia", "kingdom of Macedonia"),
    ("ma Macedonia", "Macedonia"),
    ("kingdom of phas", "kingdom of Paeonia"),
    ("then you havea over here", "then you have Epirus over here"),
    ("place called FIS", "place called Thessaly"),
    ("ayia attacked", "Illyria attacked"),
    ("Army th attacked", "Army Thebes attacked"),
    ("p par Monon parmenion", "Parmenion"),
    ("that permanon would", "that Parmenion would"),
    ("trusted p parmenion", "trusted Parmenion"),
    ("permanon would", "Parmenion would"),
    ("region okay", "regent okay"),
    ("became region", "became regent"),
    ("as region", "as regent"),
    ("the phic ", "the phalanx "),
    ("the phic breaks", "the phalanx breaks"),
    ("to the phic", "to the phalanx"),
    ("changes to the phic", "changes to the phalanx"),
    ("the Finks", "the phalanx"),
    ("phenx", "phalanx"),
    ("horation", "horsemen"),
    (" and ACC ", " and cavalry "),
    ("action of the great", "Alexander the Great"),
    ("in here a the Great", "Alexander the Great"),
    ("C all Persia", "conquer all Persia"),
    ("mstone", "Macedonian"),
    ("macons", "Macedonians"),
    ("madon", "Macedon"),
    ("maedon", "Macedon"),
    ("controlling Mason", "controlling Macedon"),
    ("philli II", "Philip II"),
    (" philli ", " Philip "),
    ("BC philli ", "BC Philip "),
    ("Phil philli", "Philip"),
    ("shooted", "treated"),
    ("roades", "roads"),
    ("kingom", "kingdom"),
    ("multip okay", "multiple okay"),
    ("amphibolis", "Amphipolis"),
    # Remaining “thieves” → Thebes: handled in asr_light_clean.fix_civilization_thieves
]
