"""Render ANALYSIS-BACKLOG.md from sources, source-map, and book-architecture."""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
WORK_DIR = ROOT / "research" / "external" / "work-jiang"
OUT = WORK_DIR / "ANALYSIS-BACKLOG.md"


def load(path: Path) -> dict:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def priority_for_source(
    source: dict,
    mapped_chapters: list[str],
    chapters: list[dict],
    next_in_queue_statuses: set[str],
) -> int:
    """Score 0+; higher = more urgent. Blocks next chapter +100, sprint +50, geo +20, missing +10."""
    score = 0
    sid = source.get("source_id", "")
    analysis_complete = (source.get("status") or {}).get("analysis") == "complete"

    for ch in chapters:
        if ch.get("status") in next_in_queue_statuses:
            sids = ch.get("source_ids") or []
            if sid in sids:
                score += 100
                break

    if mapped_chapters:
        score += 50
    if source.get("series") == "geo-strategy":
        score += 20
    if not analysis_complete:
        score += 10

    return score


def main() -> int:
    sources = load(WORK_DIR / "metadata" / "sources.yaml").get("sources", [])
    sm = load(WORK_DIR / "metadata" / "source-map.yaml")
    arch = load(WORK_DIR / "metadata" / "book-architecture.yaml")
    chapter_map = sm.get("chapter_map") or {}
    chapters = (arch.get("book") or {}).get("chapters") or []

    next_in_queue = {"ready_for_outline", "analysis_complete"}

    rows = []
    for s in sources:
        sid = s.get("source_id", "")
        mapped = [
            cid
            for cid, data in chapter_map.items()
            if sid in (data.get("source_ids") or [])
        ]
        score = priority_for_source(s, mapped, chapters, next_in_queue)
        analysis_status = (s.get("status") or {}).get("analysis", "missing")
        reason_parts = []
        if score >= 100:
            reason_parts.append("blocks next chapter in queue")
        if mapped:
            reason_parts.append(f"mapped to {', '.join(mapped)}")
        if s.get("series") == "geo-strategy":
            reason_parts.append("geo-series")
        if analysis_status != "complete":
            reason_parts.append("analysis missing")
        reason = "; ".join(reason_parts) if reason_parts else "—"
        rows.append(
            {
                "source_id": sid,
                "series": s.get("series", ""),
                "lecture_title": s.get("title", ""),
                "analysis_status": analysis_status,
                "mapped_chapters": ", ".join(mapped) if mapped else "—",
                "priority_score": score,
                "reason": reason,
            }
        )

    rows.sort(key=lambda r: -r["priority_score"])

    lines = [
        "# ANALYSIS BACKLOG",
        "",
        "Sources missing or needing analysis, ordered by priority.",
        "",
        "| source_id | series | lecture_title | analysis_status | mapped_chapters | priority_score | reason |",
        "|-----------|--------|---------------|-----------------|-----------------|----------------|--------|",
    ]
    for r in rows:
        title = (r["lecture_title"] or "")[:50] + ("…" if len(r["lecture_title"] or "") > 50 else "")
        lines.append(
            f"| {r['source_id']} | {r['series']} | {title} | {r['analysis_status']} | "
            f"{r['mapped_chapters']} | {r['priority_score']} | {r['reason']} |"
        )
    lines.append("")
    lines.append(
        "*Generated by `scripts/work_jiang/render_analysis_backlog.py` — run after registry/source updates.*"
    )
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
