"""Render STATUS.md — corpus, book, registries, next actions."""
from __future__ import annotations

import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
WORK_DIR = ROOT / "research" / "external" / "work-jiang"
OUT = WORK_DIR / "STATUS.md"


def load_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def count_geo_lectures() -> int:
    return len(list((WORK_DIR / "lectures").glob("geo-strategy-*.md")))


def main() -> int:
    sources = load_yaml(WORK_DIR / "metadata" / "sources.yaml").get("sources", [])
    chapters = load_yaml(WORK_DIR / "metadata" / "chapter-queue.yaml").get("chapter_queue", [])
    arch = load_yaml(WORK_DIR / "metadata" / "book-architecture.yaml")
    pred_links = load_yaml(WORK_DIR / "metadata" / "prediction-links.yaml")
    div_links = load_yaml(WORK_DIR / "metadata" / "divergence-links.yaml")
    infl_links = load_yaml(WORK_DIR / "metadata" / "influence-links.yaml")

    lecture_count = count_geo_lectures()
    analysis_count = len(list((WORK_DIR / "analysis").glob("*.md")))
    # exclude .gitkeep if counted as file - glob *.md only real files
    missing_analysis = [s["source_id"] for s in sources if s["status"]["analysis"] != "complete"]

    preds_raw = load_jsonl(WORK_DIR / "prediction-tracking" / "registry" / "predictions.jsonl")
    divs_raw = load_jsonl(WORK_DIR / "divergence-tracking" / "registry" / "divergences.jsonl")
    infl_raw = load_jsonl(WORK_DIR / "influence-tracking" / "snapshots" / "video-metrics.jsonl")

    pl = pred_links.get("prediction_links") if isinstance(pred_links, dict) else None
    pred_linked = len(pl) if isinstance(pl, list) else len(preds_raw)

    unresolved = sum(
        1
        for p in preds_raw
        if (p.get("resolution_status") or "") in ("pending", "not_evaluable", "")
        or p.get("resolved_at_utc") is None
    )

    dl = div_links.get("divergence_links") if isinstance(div_links, dict) else None
    div_linked = len(dl) if isinstance(dl, list) else len(divs_raw)

    il = infl_links.get("influence_links") if isinstance(infl_links, dict) else None
    infl_count = len(il) if isinstance(il, list) else len(infl_raw)

    arch_ch = (arch.get("book") or {}).get("chapters") or []
    thesis_state = (arch.get("project") or {}).get("status", "unknown")

    ready_now = [
        c
        for c in chapters
        if c.get("status") in ("research_ready", "ready_for_outline", "draft_in_progress")
    ]
    blocked = [c for c in chapters if c.get("blocking_items")]

    lines = [
        "# work-jiang — status",
        "",
        "> Operator lane — not Voice knowledge until merged through the gate.",
        "",
        "## Corpus",
        "",
        f"- **Geo-Strategy lectures:** {lecture_count}",
        f"- **Analysis memos:** {analysis_count}",
        f"- **Missing analysis:** {len(missing_analysis)} ({', '.join(missing_analysis) if missing_analysis else 'none'})",
        "",
        "## Book architecture",
        "",
        f"- **Project status:** {thesis_state}",
        f"- **Chapters defined:** {len(arch_ch)}",
        f"- **Chapters in queue:** {len(chapters)}",
        f"- **Chapters research-ready or ready for outline:** {len(ready_now)}",
        f"- **Chapters with blockers listed:** {len(blocked)}",
        "",
        "## Registries",
        "",
        f"- **Predictions (raw jsonl):** {len(preds_raw)}",
        f"- **Predictions linked (metadata):** {pred_linked}",
        f"- **Unresolved / pending predictions (heuristic):** {unresolved}",
        f"- **Divergences (raw jsonl):** {len(divs_raw)}",
        f"- **Divergences linked (metadata):** {div_linked}",
        f"- **Influence snapshots:** {infl_count}",
        "",
        "## Next actions",
        "",
    ]
    for i, c in enumerate(chapters[:5], 1):
        lines.append(f"{i}. {c.get('next_action', '')} ({c.get('chapter_id', '')})")
    if not chapters:
        lines.append("1. (Define chapter queue in metadata/chapter-queue.yaml)")
    lines.append("")
    lines.append(
        "*Generated by `scripts/work_jiang/render_status_dashboard.py` — run after registry/link updates.*"
    )
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
